/* The following code was generated by JFlex 1.4.3 on 2/6/13 7:46 PM */

/* keywords */

/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 2/6/13 7:46 PM from the specification file
 * <tt>/home/navin/personal/projects/java/ComplexAttributes/complex_attributes.flex</tt>
 */
class Lexer implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\10\1\12\4\0\16\10\4\0\1\12\3\0\1\10\2\0\1\11"+
    "\1\1\1\2\2\0\1\5\3\0\12\7\1\6\6\0\32\10\4\0"+
    "\1\10\1\0\1\20\1\10\1\14\1\24\1\16\1\10\1\25\1\15"+
    "\1\21\3\10\1\17\1\22\3\10\1\26\1\13\1\23\6\10\1\3"+
    "\1\0\1\4\1\0\41\10\2\0\4\10\4\0\1\10\2\0\1\10"+
    "\7\0\1\10\4\0\1\10\5\0\27\10\1\0\37\10\1\0\u01ca\10"+
    "\4\0\14\10\16\0\5\10\7\0\1\10\1\0\1\10\21\0\165\10"+
    "\1\0\2\10\2\0\4\10\10\0\1\10\1\0\3\10\1\0\1\10"+
    "\1\0\24\10\1\0\123\10\1\0\213\10\1\0\5\10\2\0\236\10"+
    "\11\0\46\10\2\0\1\10\7\0\47\10\11\0\55\10\1\0\1\10"+
    "\1\0\2\10\1\0\2\10\1\0\1\10\10\0\33\10\5\0\3\10"+
    "\15\0\4\10\7\0\1\10\4\0\13\10\5\0\100\10\12\7\4\0"+
    "\146\10\1\0\11\10\1\0\12\10\1\0\6\10\12\7\3\10\2\0"+
    "\1\10\17\0\74\10\2\0\145\10\16\0\12\7\54\10\4\0\1\10"+
    "\5\0\56\10\22\0\34\10\244\0\144\10\2\0\12\7\1\0\7\10"+
    "\1\0\7\10\1\0\3\10\1\0\10\10\2\0\2\10\2\0\26\10"+
    "\1\0\7\10\1\0\1\10\3\0\4\10\2\0\11\10\2\0\2\10"+
    "\2\0\4\10\10\0\1\10\4\0\2\10\1\0\5\10\2\0\12\7"+
    "\4\10\7\0\1\10\5\0\3\10\1\0\6\10\4\0\2\10\2\0"+
    "\26\10\1\0\7\10\1\0\2\10\1\0\2\10\1\0\2\10\2\0"+
    "\1\10\1\0\5\10\4\0\2\10\2\0\3\10\3\0\1\10\7\0"+
    "\4\10\1\0\1\10\7\0\12\7\6\10\13\0\3\10\1\0\11\10"+
    "\1\0\3\10\1\0\26\10\1\0\7\10\1\0\2\10\1\0\5\10"+
    "\2\0\12\10\1\0\3\10\1\0\3\10\2\0\1\10\17\0\4\10"+
    "\2\0\12\7\1\0\1\10\17\0\3\10\1\0\10\10\2\0\2\10"+
    "\2\0\26\10\1\0\7\10\1\0\2\10\1\0\5\10\2\0\11\10"+
    "\2\0\2\10\2\0\3\10\10\0\2\10\4\0\2\10\1\0\5\10"+
    "\2\0\12\7\1\0\1\10\20\0\2\10\1\0\6\10\3\0\3\10"+
    "\1\0\4\10\3\0\2\10\1\0\1\10\1\0\2\10\3\0\2\10"+
    "\3\0\3\10\3\0\14\10\4\0\5\10\3\0\3\10\1\0\4\10"+
    "\2\0\1\10\6\0\1\10\16\0\12\7\11\0\1\10\7\0\3\10"+
    "\1\0\10\10\1\0\3\10\1\0\27\10\1\0\12\10\1\0\5\10"+
    "\3\0\10\10\1\0\3\10\1\0\4\10\7\0\2\10\1\0\2\10"+
    "\6\0\4\10\2\0\12\7\22\0\2\10\1\0\10\10\1\0\3\10"+
    "\1\0\27\10\1\0\12\10\1\0\5\10\2\0\11\10\1\0\3\10"+
    "\1\0\4\10\7\0\2\10\7\0\1\10\1\0\4\10\2\0\12\7"+
    "\1\0\2\10\17\0\2\10\1\0\10\10\1\0\3\10\1\0\51\10"+
    "\2\0\10\10\1\0\3\10\1\0\5\10\10\0\1\10\10\0\4\10"+
    "\2\0\12\7\12\0\6\10\2\0\2\10\1\0\22\10\3\0\30\10"+
    "\1\0\11\10\1\0\1\10\2\0\7\10\3\0\1\10\4\0\6\10"+
    "\1\0\1\10\1\0\10\10\22\0\2\10\15\0\72\10\4\0\20\10"+
    "\1\0\12\7\47\0\2\10\1\0\1\10\2\0\2\10\1\0\1\10"+
    "\2\0\1\10\6\0\4\10\1\0\7\10\1\0\3\10\1\0\1\10"+
    "\1\0\1\10\2\0\2\10\1\0\15\10\1\0\3\10\2\0\5\10"+
    "\1\0\1\10\1\0\6\10\2\0\12\7\2\0\2\10\42\0\1\10"+
    "\27\0\2\10\6\0\12\7\13\0\1\10\1\0\1\10\1\0\1\10"+
    "\4\0\12\10\1\0\44\10\4\0\24\10\1\0\22\10\1\0\44\10"+
    "\11\0\1\10\71\0\100\10\12\7\6\0\100\10\12\7\4\10\2\0"+
    "\46\10\12\0\53\10\1\0\1\10\3\0\u0149\10\1\0\4\10\2\0"+
    "\7\10\1\0\1\10\1\0\4\10\2\0\51\10\1\0\4\10\2\0"+
    "\41\10\1\0\4\10\2\0\7\10\1\0\1\10\1\0\4\10\2\0"+
    "\17\10\1\0\71\10\1\0\4\10\2\0\103\10\2\0\3\10\40\0"+
    "\20\10\20\0\125\10\14\0\u026c\10\2\0\21\10\1\0\32\10\5\0"+
    "\113\10\3\0\3\10\17\0\15\10\1\0\7\10\13\0\25\10\13\0"+
    "\24\10\14\0\15\10\1\0\3\10\1\0\2\10\14\0\124\10\3\0"+
    "\1\10\3\0\3\10\2\0\12\7\41\0\3\10\2\0\12\7\6\0"+
    "\130\10\10\0\53\10\5\0\106\10\12\0\35\10\3\0\14\10\4\0"+
    "\14\10\12\0\12\7\36\10\2\0\5\10\13\0\54\10\4\0\32\10"+
    "\6\0\12\7\46\0\34\10\4\0\77\10\1\0\35\10\2\0\1\10"+
    "\12\7\6\0\12\7\15\0\1\10\130\0\114\10\4\0\12\7\21\0"+
    "\11\10\14\0\53\10\3\0\2\10\12\7\6\0\64\10\14\0\70\10"+
    "\10\0\12\7\3\0\3\10\12\7\44\10\122\0\3\10\1\0\37\10"+
    "\15\0\347\10\25\0\u011a\10\2\0\6\10\2\0\46\10\2\0\6\10"+
    "\2\0\10\10\1\0\1\10\1\0\1\10\1\0\1\10\1\0\37\10"+
    "\2\0\65\10\1\0\7\10\1\0\1\10\3\0\3\10\1\0\7\10"+
    "\3\0\4\10\2\0\6\10\4\0\15\10\5\0\3\10\1\0\7\10"+
    "\16\0\5\10\32\0\5\10\20\0\2\10\23\0\1\10\13\0\5\10"+
    "\5\0\6\10\1\0\1\10\15\0\1\10\20\0\15\10\3\0\32\10"+
    "\26\0\15\10\4\0\1\10\3\0\14\10\21\0\1\10\4\0\1\10"+
    "\2\0\12\10\1\0\1\10\3\0\5\10\6\0\1\10\1\0\1\10"+
    "\1\0\1\10\1\0\4\10\1\0\13\10\2\0\4\10\5\0\5\10"+
    "\4\0\1\10\21\0\51\10\u0a77\0\57\10\1\0\57\10\1\0\205\10"+
    "\6\0\7\10\16\0\46\10\12\0\66\10\11\0\1\10\17\0\30\10"+
    "\11\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10\1\0\7\10"+
    "\1\0\7\10\1\0\7\10\1\0\7\10\1\0\40\10\57\0\1\10"+
    "\u01d5\0\3\10\31\0\17\10\1\0\5\10\2\0\5\10\4\0\126\10"+
    "\2\0\2\10\2\0\3\10\1\0\132\10\1\0\4\10\5\0\51\10"+
    "\3\0\136\10\21\0\33\10\65\0\20\10\u0200\0\u19b6\10\112\0\u51cc\10"+
    "\64\0\u048d\10\103\0\56\10\2\0\u010d\10\3\0\20\10\12\7\2\10"+
    "\24\0\60\10\14\0\2\10\1\0\31\10\10\0\122\10\45\0\11\10"+
    "\2\0\147\10\2\0\4\10\1\0\2\10\16\0\12\10\120\0\56\10"+
    "\20\0\1\10\7\0\64\10\14\0\105\10\13\0\12\7\6\0\30\10"+
    "\3\0\1\10\4\0\12\7\44\10\2\0\44\10\14\0\35\10\3\0"+
    "\101\10\16\0\1\10\12\7\46\0\67\10\11\0\16\10\2\0\12\7"+
    "\6\0\27\10\3\0\2\10\4\0\103\10\30\0\3\10\43\0\6\10"+
    "\2\0\6\10\2\0\6\10\11\0\7\10\1\0\7\10\221\0\53\10"+
    "\1\0\2\10\2\0\12\7\6\0\u2ba4\10\14\0\27\10\4\0\61\10"+
    "\u2104\0\u012e\10\2\0\76\10\2\0\152\10\46\0\7\10\14\0\5\10"+
    "\5\0\14\10\1\0\15\10\1\0\5\10\1\0\1\10\1\0\2\10"+
    "\1\0\2\10\1\0\154\10\41\0\u016b\10\22\0\100\10\2\0\66\10"+
    "\50\0\15\10\3\0\20\10\20\0\7\10\14\0\2\10\30\0\3\10"+
    "\31\0\1\10\6\0\5\10\1\0\207\10\2\0\1\10\4\0\1\10"+
    "\13\0\12\7\7\0\32\10\4\0\1\10\1\0\32\10\13\0\131\10"+
    "\3\0\6\10\2\0\6\10\2\0\6\10\2\0\3\10\3\0\2\10"+
    "\3\0\2\10\22\0\3\10\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\1\1\2\1\3\1\4\1\5\1\6\1\7\1\1"+
    "\1\10\1\0\1\11\3\10\1\12\6\10\1\13\12\10"+
    "\1\14\1\15\3\10\1\16\1\10\1\17";

  private static int [] zzUnpackAction() {
    int [] result = new int[40];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\27\0\27\0\27\0\27\0\27\0\27\0\56"+
    "\0\105\0\134\0\163\0\212\0\241\0\270\0\27\0\317"+
    "\0\346\0\375\0\u0114\0\u012b\0\u0142\0\105\0\u0159\0\u0170"+
    "\0\u0187\0\u019e\0\u01b5\0\u01cc\0\u01e3\0\u01fa\0\u0211\0\u0228"+
    "\0\105\0\105\0\u023f\0\u0256\0\u026d\0\105\0\u0284\0\105";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[40];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\0\1\2\1\3\1\4\1\5\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\2\11\1\15\2\11\1\16"+
    "\5\11\36\0\1\10\1\11\2\0\14\11\7\0\2\11"+
    "\2\0\14\11\7\0\2\12\1\17\1\0\14\12\12\0"+
    "\1\13\23\0\2\11\2\0\1\11\1\20\6\11\1\21"+
    "\3\11\7\0\2\11\2\0\7\11\1\22\4\11\7\0"+
    "\2\11\2\0\7\11\1\23\4\11\7\0\2\11\2\0"+
    "\2\11\1\24\11\11\7\0\2\11\2\0\13\11\1\25"+
    "\7\0\2\11\2\0\11\11\1\26\2\11\7\0\2\11"+
    "\2\0\1\27\7\11\1\30\3\11\7\0\2\11\2\0"+
    "\3\11\1\31\10\11\7\0\2\11\2\0\6\11\1\32"+
    "\5\11\7\0\2\11\2\0\10\11\1\33\3\11\7\0"+
    "\2\11\2\0\3\11\1\34\10\11\7\0\2\11\2\0"+
    "\4\11\1\35\7\11\7\0\2\11\2\0\7\11\1\36"+
    "\4\11\7\0\2\11\2\0\5\11\1\37\6\11\7\0"+
    "\2\11\2\0\12\11\1\40\1\11\7\0\2\11\2\0"+
    "\5\11\1\41\6\11\7\0\2\11\2\0\12\11\1\42"+
    "\1\11\7\0\2\11\2\0\7\11\1\43\4\11\7\0"+
    "\2\11\2\0\3\11\1\44\10\11\7\0\2\11\2\0"+
    "\1\11\1\45\12\11\7\0\2\11\2\0\13\11\1\46"+
    "\7\0\2\11\2\0\3\11\1\47\10\11\7\0\2\11"+
    "\2\0\1\50\13\11";

  private static int [] zzUnpackTrans() {
    int [] result = new int[667];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\1\6\11\2\1\1\0\4\1\1\11\31\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[40];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  Lexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  Lexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 1890) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 14: 
          { return symbol(sym.INTEGER);
          }
        case 16: break;
        case 11: 
          { return symbol(sym.END);
          }
        case 17: break;
        case 7: 
          { return symbol(sym.COLON);
          }
        case 18: break;
        case 1: 
          { return symbol(sym.INTEGERVAL);
          }
        case 19: break;
        case 15: 
          { return symbol(sym.INSTANCES);
          }
        case 20: break;
        case 13: 
          { return symbol(sym.STRING);
          }
        case 21: break;
        case 12: 
          { return symbol(sym.SCHEMA);
          }
        case 22: break;
        case 3: 
          { return symbol(sym.RPAREN);
          }
        case 23: break;
        case 2: 
          { return symbol(sym.LPAREN);
          }
        case 24: break;
        case 10: 
          { return symbol(sym.STRINGVAL);
          }
        case 25: break;
        case 6: 
          { return symbol(sym.COMMA);
          }
        case 26: break;
        case 8: 
          { return symbol(sym.ATTRIBUTE);
          }
        case 27: break;
        case 5: 
          { return symbol(sym.RBRACE);
          }
        case 28: break;
        case 9: 
          { 
          }
        case 29: break;
        case 4: 
          { return symbol(sym.LBRACE);
          }
        case 30: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
              { return new java_cup.runtime.Symbol(sym.EOF); }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
