
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Wed Feb 06 22:09:13 EST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LBRACE = 9;
  public static final int INTEGER = 12;
  public static final int STRINGVAL = 15;
  public static final int COLON = 11;
  public static final int INTEGERVAL = 14;
  public static final int SCHEMA = 2;
  public static final int INSTANCES = 3;
  public static final int STRING = 13;
  public static final int EOF = 0;
  public static final int ATTRIBUTE = 5;
  public static final int COMMA = 8;
  public static final int error = 1;
  public static final int RPAREN = 7;
  public static final int RBRACE = 10;
  public static final int END = 4;
  public static final int LPAREN = 6;
}

